# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Prompting CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        bash scripts/install.sh
        poetry install --all-extras

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "12.22.9"

    - name: Debug Environment
      run: |
        poetry run python -V
        poetry run which python
        poetry env info
        poetry run pip list

    # Style/format checks.
    - name: Run Black (code formatter)
      run: |
        poetry run black --check --diff .

    - name: Run isort (import sorting)
      run: |
        poetry run isort --check-only --diff --profile black .

    - name: Run Ruff (linter)
      run: |
        poetry run ruff check --diff .

    - name: Test with pytest
      run: |
        # run tests in tests/ dir and only fail if there are failures or errors
        poetry run pytest tests/ --verbose --failed-first --exitfirst --disable-warnings

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
